# Generated by Django 2.2 on 2019-04-30 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reiwa_app', '0002_auto_20190429_0201'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='photo',
            field=models.ImageField(default='defo', upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(upload_to='documents/', verbose_name=''),
        ),
    ]
